# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'libraries/kirigami-addons': '@latest-kf6'
    
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Flatpack', 'Android/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'libraries/kirigami-addons': '@latest'
